# Generated by Django 5.0.4 on 2024-05-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassActivity',
            fields=[
                ('name', models.CharField(max_length=900)),
                ('discription', models.CharField(max_length=900)),
                ('slug', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(choices=[('Event', 'Event'), ('Class', 'Class'), ('Venue', 'Venue')], max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_img', models.ImageField(upload_to='event_pics')),
                ('capcity', models.IntegerField()),
                ('landmark', models.CharField(max_length=900)),
                ('parent_tag', models.CharField(choices=[('Social Events', 'Social Events'), ('Cultural Events', 'Cultural Events'), ('Educational Events', 'Educational Events'), ('Sporting Events', 'Sporting Events'), ('Political Events', 'Political Events'), ('Entertainment Events', 'Entertainment Events'), ('Fundraising Events', 'Fundraising Events')], max_length=600)),
                ('location', models.CharField(max_length=600)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('priority', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('booking', models.CharField(choices=[('Ticket', 'Ticket'), ('Slote', 'Slote')], max_length=90)),
                ('public_orgnaization', models.CharField(blank=True, choices=[('National Geographic Society', 'National Geographic Society'), ('Red Cross/Red Crescent Societies', 'Red Cross/Red Crescent Societies'), ('Greenpeace', 'Greenpeace'), ('Amnesty International', 'Amnesty International'), ('Smithsonian Institution', 'Smithsonian Institution'), ('World Wildlife Fund (WWF)', 'World Wildlife Fund (WWF)'), ('European Space Agency (ESA)', 'European Space Agency (ESA):')], max_length=900, null=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Not Pubished', 'Not Pubished')], max_length=100)),
                ('select_sports', models.CharField(choices=[('Basketball', 'Basketball'), ('Football', 'Football'), ('Swimming', 'Swimming'), ('Volley Ball', 'Volley Ball'), ('Music', 'Music')], max_length=600)),
                ('stundent_leval', models.CharField(choices=[('Beginner', 'Beginner'), ('InterMediate', 'InterMediate'), ('Expert', 'Expert')], max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('name', models.CharField(max_length=900)),
                ('discription', models.CharField(max_length=900)),
                ('slug', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(choices=[('Event', 'Event'), ('Class', 'Class'), ('Venue', 'Venue')], max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_img', models.ImageField(upload_to='event_pics')),
                ('capcity', models.IntegerField()),
                ('landmark', models.CharField(max_length=900)),
                ('parent_tag', models.CharField(choices=[('Social Events', 'Social Events'), ('Cultural Events', 'Cultural Events'), ('Educational Events', 'Educational Events'), ('Sporting Events', 'Sporting Events'), ('Political Events', 'Political Events'), ('Entertainment Events', 'Entertainment Events'), ('Fundraising Events', 'Fundraising Events')], max_length=600)),
                ('location', models.CharField(max_length=600)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('priority', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('booking', models.CharField(choices=[('Ticket', 'Ticket'), ('Slote', 'Slote')], max_length=90)),
                ('public_orgnaization', models.CharField(blank=True, choices=[('National Geographic Society', 'National Geographic Society'), ('Red Cross/Red Crescent Societies', 'Red Cross/Red Crescent Societies'), ('Greenpeace', 'Greenpeace'), ('Amnesty International', 'Amnesty International'), ('Smithsonian Institution', 'Smithsonian Institution'), ('World Wildlife Fund (WWF)', 'World Wildlife Fund (WWF)'), ('European Space Agency (ESA)', 'European Space Agency (ESA):')], max_length=900, null=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Not Pubished', 'Not Pubished')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
