# Generated by Django 5.0.4 on 2024-05-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_classactivity_sportsandarts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('name', models.CharField(max_length=900)),
                ('discription', models.CharField(max_length=900)),
                ('slug', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(choices=[('Event', 'Event'), ('Class', 'Class'), ('Venue', 'Venue')], max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_img', models.ImageField(upload_to='event_pics')),
                ('capcity', models.IntegerField()),
                ('landmark', models.CharField(max_length=900)),
            ],
        ),
        migrations.RenameField(
            model_name='sportsandarts',
            old_name='slug',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='slug',
            new_name='event_id',
        ),
        migrations.RemoveField(
            model_name='sportsandarts',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='sportsandarts',
            name='capcity',
        ),
        migrations.RemoveField(
            model_name='sportsandarts',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='sportsandarts',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='sportsandarts',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='sportsandarts',
            name='event_img',
        ),
        migrations.RemoveField(
            model_name='sportsandarts',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='sportsandarts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sportsandarts',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='sportsandarts',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='capcity',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='event_img',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='name',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='start_time',
        ),
    ]
