# Generated by Django 5.0.4 on 2024-05-09 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_activity_rename_slug_sportsandarts_event_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='capcity',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='event_img',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_time',
        ),
        migrations.AddField(
            model_name='sportsandarts',
            name='capcity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sportsandarts',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 5, 9)),
        ),
        migrations.AddField(
            model_name='sportsandarts',
            name='end_time',
            field=models.DateTimeField(default=datetime.time(16, 44, 41, 452339)),
        ),
        migrations.AddField(
            model_name='sportsandarts',
            name='event_img',
            field=models.ImageField(default=datetime.time(16, 44, 41, 452339), upload_to='event_pics'),
        ),
        migrations.AddField(
            model_name='sportsandarts',
            name='landmark',
            field=models.CharField(default=datetime.date(2024, 5, 9), max_length=900),
        ),
        migrations.AddField(
            model_name='sportsandarts',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 5, 9)),
        ),
        migrations.AddField(
            model_name='sportsandarts',
            name='start_time',
            field=models.DateTimeField(default=datetime.time(16, 44, 41, 452339)),
        ),
        migrations.AddField(
            model_name='venue',
            name='capcity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='venue',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 5, 9)),
        ),
        migrations.AddField(
            model_name='venue',
            name='end_time',
            field=models.DateTimeField(default=datetime.time(16, 44, 41, 452339)),
        ),
        migrations.AddField(
            model_name='venue',
            name='event_img',
            field=models.ImageField(default=datetime.time(16, 44, 41, 452339), upload_to='event_pics'),
        ),
        migrations.AddField(
            model_name='venue',
            name='landmark',
            field=models.CharField(default=datetime.date(2024, 5, 9), max_length=900),
        ),
        migrations.AddField(
            model_name='venue',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 5, 9)),
        ),
        migrations.AddField(
            model_name='venue',
            name='start_time',
            field=models.DateTimeField(default=datetime.time(16, 44, 41, 452339)),
        ),
        migrations.AlterField(
            model_name='sportsandarts',
            name='booking',
            field=models.CharField(choices=[('Ticket', 'Ticket'), ('Slot', 'Slot')], max_length=90),
        ),
        migrations.AlterField(
            model_name='sportsandarts',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Not Published', 'Not Published')], max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='booking',
            field=models.CharField(choices=[('Ticket', 'Ticket'), ('Slot', 'Slot')], max_length=90),
        ),
        migrations.AlterField(
            model_name='venue',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Not Published', 'Not Published')], max_length=100),
        ),
    ]
