# Generated by Django 5.0.4 on 2024-05-09 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_sportsandarts_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsandarts',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sportsandarts',
            name='event_img',
            field=models.ImageField(default=datetime.time(16, 50, 39, 602868), upload_to='event_pics'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='event_img',
            field=models.ImageField(default=datetime.time(16, 50, 39, 602868), upload_to='event_pics'),
        ),
    ]
