# Generated by Django 5.0.4 on 2024-05-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_sportsandarts_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsandarts',
            name='event_img',
            field=models.ImageField(upload_to='event_pics'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='event_img',
            field=models.ImageField(upload_to='event_pics'),
        ),
    ]
