# Generated by Django 5.0.4 on 2024-05-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_sportsandarts_event_img_alter_venue_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsandarts',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='end_date',
            field=models.DateField(),
        ),
    ]
