# Generated by Django 5.0.4 on 2024-05-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_sportsandarts_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsandarts',
            name='landmark',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='venue',
            name='landmark',
            field=models.CharField(max_length=900),
        ),
    ]
