# Generated by Django 5.0.4 on 2024-05-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_sportsandarts_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsandarts',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sportsandarts',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sportsandarts',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
