# Generated by Django 5.0.4 on 2024-05-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_sportsandarts_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsandarts',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
