# Generated by Django 5.0.4 on 2024-05-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_sportsandarts_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsandarts',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='sportsandarts',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='start_time',
        ),
    ]
