# Generated by Django 5.0.4 on 2024-05-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_sportsandarts_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsandarts',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportsandarts',
            name='start_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
