# Generated by Django 5.0.4 on 2024-05-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_sportsandarts_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('event_img', models.ImageField(upload_to='event_pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='sportsandarts',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='sportsandarts',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='sportsandarts',
            name='event_img',
        ),
        migrations.RemoveField(
            model_name='sportsandarts',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='sportsandarts',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='event_img',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='start_time',
        ),
    ]
