# Generated by Django 4.2.4 on 2023-08-12 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0005_repeated_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='alternative_phone_no',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='alternative_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='staff_type',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('Faculty', 'Faculty'), ('Counsellor', 'Counsellor'), ('Accountant', 'Accountant')], max_length=12),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='course',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='course_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='declaration',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='declaration_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='gender',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='mode_of_class',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 2, 40, 38, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='office',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='payment_method',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='payment_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='reference_contact_number',
            field=models.CharField(blank=True, default='0000000000', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status_of_enquiry',
            field=models.CharField(blank=True, default='Not Contacted', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='repeated_user',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
