# Generated by Django 4.2.4 on 2023-08-13 16:18

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0008_alter_enquiry_date_of_enquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date_of_enquiry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 9, 13, 47, 6, tzinfo=datetime.timezone.utc)),
        ),
    ]
