# Generated by Django 4.2.4 on 2023-08-14 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0009_alter_enquiry_date_of_enquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 11, 1, 4, 12, tzinfo=datetime.timezone.utc)),
        ),
    ]
