# Generated by Django 4.2.4 on 2023-08-17 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0010_alter_enquiry_next_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='updated_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 8, 12, 16, 37, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='student_registration_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='updated_by',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
