# Generated by Django 4.2.4 on 2023-08-17 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0011_enquiry_updated_date_alter_enquiry_next_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='amount_paid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 12, 21, 38, 33, tzinfo=datetime.timezone.utc)),
        ),
    ]
