# Generated by Django 4.2.4 on 2023-08-18 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0012_enquiry_amount_paid_alter_enquiry_next_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='outstanding_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='amount_paid',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 22, 7, 38, tzinfo=datetime.timezone.utc)),
        ),
    ]
