# Generated by Django 4.2.4 on 2023-08-18 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0013_enquiry_outstanding_amount_alter_enquiry_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 8, 2, 26, tzinfo=datetime.timezone.utc)),
        ),
    ]
