# Generated by Django 4.2.4 on 2023-08-18 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0014_alter_enquiry_next_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 21, 39, 59, tzinfo=datetime.timezone.utc)),
        ),
    ]
