# Generated by Django 4.2.4 on 2023-08-18 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0015_alter_enquiry_next_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='payment_receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 9, 5, 51, 44, tzinfo=datetime.timezone.utc)),
        ),
    ]
