# Generated by Django 4.2.4 on 2023-11-03 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0018_alter_enquiry_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='amount_paid',
            new_name='total_amount_paid',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 7, 8, 47, 26, tzinfo=datetime.timezone.utc)),
        ),
    ]
