# Generated by Django 4.2.4 on 2023-11-03 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0019_rename_amount_paid_enquiry_total_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='payment_remark',
            new_name='payment_History',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 26, 9, 25, 33, tzinfo=datetime.timezone.utc)),
        ),
    ]
