# Generated by Django 4.2.4 on 2023-11-03 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0020_rename_payment_remark_enquiry_payment_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 23, 2, 1, 38, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='payment_History',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
