# Generated by Django 4.2.4 on 2023-11-03 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0022_alter_enquiry_next_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 24, 21, 15, 4, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='payment_History',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
