# Generated by Django 5.0.4 on 2024-05-06 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0026_alter_enquiry_next_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='certificate',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='exam',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='project_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 19, 4, 34, 19, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='office',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='year_of_pass',
            field=models.IntegerField(default=2024),
        ),
    ]
