# Generated by Django 5.0.4 on 2024-05-12 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0028_courses_joined_date_enquiry_course_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id_of_attendence', models.AutoField(primary_key=True, serialize=False)),
                ('attendence_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField()),
                ('status', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 5, 23, 23, 22, tzinfo=datetime.timezone.utc)),
        ),
    ]
