# Generated by Django 5.0.4 on 2024-05-12 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0029_attendence_alter_enquiry_next_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 20, 14, 16, 24, tzinfo=datetime.timezone.utc)),
        ),
    ]
