# Generated by Django 5.0.4 on 2024-05-13 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0030_alter_enquiry_next_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='status',
            new_name='present',
        ),
        migrations.AddField(
            model_name='attendence',
            name='absent',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 2, 5, 11, 29, tzinfo=datetime.timezone.utc)),
        ),
    ]
