# Generated by Django 5.0.4 on 2024-05-13 12:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0031_rename_status_attendence_present_attendence_absent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cbtech_app.attendence'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 24, 7, 19, 44, tzinfo=datetime.timezone.utc)),
        ),
    ]
