# Generated by Django 5.0.4 on 2024-05-13 12:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0033_alter_enquiry_name_alter_enquiry_next_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbtech_app.enquiry'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 16, 2, 45, 34, tzinfo=datetime.timezone.utc)),
        ),
    ]
