# Generated by Django 5.0.4 on 2024-05-13 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0034_attendence_connection_alter_enquiry_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 17, 4, 52, 5, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Attendence',
        ),
    ]
