# Generated by Django 5.0.4 on 2024-05-13 16:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0035_alter_enquiry_next_due_date_delete_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 13, 15, 0, 40, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id_of_attendence', models.AutoField(primary_key=True, serialize=False)),
                ('attendence_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField()),
                ('present', models.CharField(max_length=200, null=True)),
                ('absent', models.CharField(max_length=50, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbtech_app.enquiry')),
            ],
        ),
    ]
