# Generated by Django 5.0.4 on 2024-05-14 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0036_alter_enquiry_next_due_date_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 25, 10, 20, 16, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Attendence',
        ),
    ]
