# Generated by Django 5.0.4 on 2024-05-16 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0038_alter_enquiry_next_due_date_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='course_completion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 17, 14, 2, 59, tzinfo=datetime.timezone.utc)),
        ),
    ]
