# Generated by Django 5.0.4 on 2024-05-16 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtech_app', '0039_enquiry_course_completion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='placement_session_attended',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_due_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 3, 11, 57, 31, tzinfo=datetime.timezone.utc)),
        ),
    ]
