# Generated by Django 5.0.4 on 2024-05-10 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendencereport',
            name='student_id',
        ),
        migrations.AddField(
            model_name='attendence',
            name='student_registration_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
        migrations.AddField(
            model_name='attendencereport',
            name='student_registration_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
        migrations.AlterField(
            model_name='attendencereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='counsillors',
            name='coun_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='counsillor_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.counsillors'),
        ),
    ]
