# Generated by Django 5.0.4 on 2024-05-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_attendencereport_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsillors',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='updated_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendencereport',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
