# Generated by Django 5.0.4 on 2024-05-11 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_counsillors_coun_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='counsillor_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.counsillors'),
        ),
    ]
