# Generated by Django 5.0.4 on 2024-05-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_attendence_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='student_registration_id',
        ),
    ]
