# Generated by Django 5.0.4 on 2024-05-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
                ('course_type', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Crash', 'Crash'), ('Project', 'Project')], max_length=10, null=True)),
                ('course_duration', models.CharField(choices=[('Full Time', 'Full Time'), ('Crash', 'Crash'), ('Project', 'Project')], default='4 Months', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('Admin', 'Administrator'), ('Faculty', 'Faculty'), ('Counsellor', 'Counsellor'), ('Accountant', 'Accountant'), ('Manager', 'Marketing Manager')], max_length=12)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
    ]
