# Generated by Django 5.0.4 on 2024-05-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='repeated_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date_repeated', models.DateField(auto_now=True)),
                ('last_enquiry_date', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
