# Generated by Django 5.0.4 on 2024-05-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_repeated_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='repeated_user',
            new_name='RepeatedUser',
        ),
    ]
