# Generated by Django 5.0.4 on 2024-05-03 10:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_repeated_user_repeateduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_registration', models.DateField(default=django.utils.timezone.now, null=True)),
                ('student_registration_id', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('status_of_enquiry', models.CharField(blank=True, default='Not Contacted', max_length=15, null=True)),
                ('name', models.CharField(max_length=180)),
                ('address', models.CharField(max_length=800)),
                ('email_id', models.CharField(max_length=300)),
                ('gender', models.CharField(blank=True, max_length=8, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=40, null=True)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('college', models.CharField(blank=True, max_length=30, null=True)),
                ('qualification', models.CharField(max_length=30, null=True)),
                ('year_of_pass', models.IntegerField(default=2024)),
                ('technical_skills', models.CharField(blank=True, max_length=60, null=True)),
                ('mode_of_class', models.CharField(blank=True, max_length=10, null=True)),
                ('consultant_name', models.CharField(default='', max_length=10)),
                ('reference_name', models.CharField(blank=True, max_length=40, null=True)),
                ('reference_contact_number', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('course', models.CharField(blank=True, max_length=20, null=True)),
                ('course_type', models.CharField(max_length=10, null=True)),
                ('office', models.CharField(blank=True, choices=[('Kadavanthra', 'Kadavanthra'), ('Trivandrum', 'Trivandrum'), ('Calicut', 'Calicut'), ('Bangalore', 'Bangalore')], default='Kadavanthra', max_length=13, null=True)),
            ],
        ),
    ]
