# Generated by Django 5.0.4 on 2024-04-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sighn_up', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sighnup_DB',
        ),
    ]
