# Generated by Django 5.0.4 on 2024-04-23 06:51

import django.db.models.deletion
import imagekit.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=790)),
                ('thump', imagekit.models.fields.ProcessedImageField(upload_to='images/')),
                ('visible', models.BooleanField(default=True)),
                ('discription', models.TextField(max_length=1039)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumDetailView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/')),
                ('thump', imagekit.models.fields.ProcessedImageField(upload_to='images/')),
                ('alt', models.CharField(default=uuid.uuid4, max_length=1200)),
                ('created', models.DateField(auto_now_add=True)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp3.albums')),
            ],
        ),
    ]
