# Generated by Django 5.0.4 on 2024-05-08 12:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_courses_sessionyearmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='session_year_id',
            field=models.ForeignKey(default=datetime.datetime(2024, 5, 8, 12, 1, 34, 902555, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='myapp.sessionyearmodel'),
        ),
    ]
