# Generated by Django 5.0.4 on 2024-04-24 06:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employi_db',
            fields=[
                ('emp_name', models.CharField(max_length=230)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_contact', models.CharField(max_length=200)),
                ('emp_role', models.CharField(max_length=200)),
                ('emp_salary', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
