# Generated by Django 5.0.4 on 2024-04-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost_db',
            name='blog_img',
            field=models.ImageField(upload_to='blog_post'),
        ),
        migrations.AlterField(
            model_name='profile_db',
            name='phone',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='profile_db',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
