# Generated by Django 5.0.4 on 2024-04-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_blogpost_db_blog_img_alter_profile_db_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_db',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
