# Generated by Django 5.0.4 on 2024-04-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_profile_db_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_db',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
