# Generated by Django 5.0.4 on 2024-04-27 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_profile_db_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_db',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.comment_db'),
        ),
    ]
